### PR TITLE
#8#14 cli interface and seeding

### LINKED ISSUE #8: Wrap the script with an external API (CLI/Python Class/…)

### LINKED ISSUE #14: Add a seed, so that a dataset could be generated multiple times.

### PR DESCRIPTION
**Pull request by milanpro**
Closes #8 Closes #14

CLI interface is build with [click](https://github.com/pallets/click), since it was default in my python config this might be in yours too.

To get usage infos type `python main.py --help`.

Seeding is only done when the option `-s` is used, else python is responsible for the seed.

### CODE REVIEW

**Review by J-L-O — APPROVED** [review]
Fixed a typo, rest looks fine

**Comment by milanpro** [comment]
words was used because it is the last parameter. Did you test if words would work like that, because i think the parameter must be words.

**Comment by bakoe** [comment]
Nice, I didn't know that seeding is that easy. Very cool! 👍

**Comment by milanpro** [comment]
fixed the words error now with switching places

**Comment by J-L-O** [comment]
That's kind of funny, because for me it doesn't work right now, but it works if you switch words and wordsfile again.

**Comment by milanpro** [comment]
really? If that is the case, you can remove words :) should be fine without it

**Comment by milanpro** [comment]
okay, i will fix this and merge it then

**Pull request merged**
