### PR TITLE
Merge issue #4 into master

### PR DESCRIPTION
**Pull request by J-L-O**
Replaces the randomly generated words with words from a dictionary. The dictionary is taken from [freeBSD](https://svnweb.freebsd.org/csrg/share/dict/words?view=co&content-type=text/plain) which, I think, means that we need to somehow reference the BSD license(?). If you know what exactly that means, feel free to do it, otherwise we should probably ask Christian on Monday.

### CODE REVIEW

**Comment by bakoe** [comment]
Regarding the licensing question:

Since the README file from the same directory as the words file you liked (https://svnweb.freebsd.org/csrg/share/dict/README?view=co&content-type=text/plain) states that …

> The 1934 copyright has elapsed, according to the supplier.

…, I’d assume that it should be okay to use it as-is. We might however add a line to our README.md explaining (a) where we got the words.txt from and (b) that the original copyright apparently has elapsed, thus making the file public domain (“Gemeinfrei”).

**Review by bakoe — APPROVED** [review]
👍 LGTM code-wise! Haven’t tried it out yet though.

**Comment by J-L-O** [comment]
Actually, I forgot to give each word its own bounding box. Shame on you for not noticing ;-)! It's fixed now though.

**Comment by bakoe** [comment]
Hmm, but I’m not sure about the expected AABB of multi-word text, actually. Is the machine learning algorithm expected to output one AABB for each word? My gut feeling was that it should output one big AABB for alle words in one “area”(?). Maybe something to clarify with Christian?

However, thanks for implementing it! Maybe we could even add a parameter to the method that allows to switch between the calculation of one AABB and multiple AABBs?

**Comment by milanpro** [comment]
Actually we asked christian about that and he told us that every word should have its own bounding box.

**Review by milanpro — APPROVED** [review]

**Pull request merged**
